In [9]:
import numpy as np
import pandas as pd

In [10]:
df=pd.read_csv("seattle-weather.csv")

In [11]:
df.head()

date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain

In [8]:
1461/30


48.7

In [12]:
df.isnull().sum()

date             0
precipitation    0
temp_max         0
temp_min         0
wind             0
weather          0
dtype: int64

In [13]:
X=df.loc[:,["precipitation","temp_max","temp_min","wind"]]


In [14]:
X

precipitation  temp_max  temp_min  wind
0               0.0      12.8       5.0   4.7
1              10.9      10.6       2.8   4.5
2               0.8      11.7       7.2   2.3
3              20.3      12.2       5.6   4.7
4               1.3       8.9       2.8   6.1
...             ...       ...       ...   ...
1456            8.6       4.4       1.7   2.9
1457            1.5       5.0       1.7   1.3
1458            0.0       7.2       0.6   2.6
1459            0.0       5.6      -1.0   3.4
1460            0.0       5.6      -2.1   3.5

[1461 rows x 4 columns]

In [15]:
y

NameError: name 'y' is not defined

In [9]:
import seaborn as sns
from matplotlib import pyplot as plt

In [16]:
df["weather"].value_counts()[0]

641

In [17]:
x=df["weather"].unique()

In [18]:
x

array(['drizzle', 'rain', 'sun', 'snow', 'fog'], dtype=object)

In [18]:
y=[]
for i in range(5):
    y.append(df['weather'].value_counts()[i])

In [19]:
y

[641, 640, 101, 53, 26]

In [19]:
plt.bar(x,y,color='red',width=0.4)

NameError: name 'plt' is not defined

## Preprocessing the data

In [20]:
from sklearn import preprocessing 
label_encoder=preprocessing.LabelEncoder()

In [21]:
df["weather"]=label_encoder.fit_transform(df["weather"])

In [22]:
df['weather'].unique()

array([0, 2, 4, 3, 1])

In [23]:
df['weather'].value_counts()

2    641
4    640
1    101
0     53
3     26
Name: weather, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score

In [27]:
sc=StandardScaler()

In [25]:
X

precipitation  temp_max  temp_min  wind
0               0.0      12.8       5.0   4.7
1              10.9      10.6       2.8   4.5
2               0.8      11.7       7.2   2.3
3              20.3      12.2       5.6   4.7
4               1.3       8.9       2.8   6.1
...             ...       ...       ...   ...
1456            8.6       4.4       1.7   2.9
1457            1.5       5.0       1.7   1.3
1458            0.0       7.2       0.6   2.6
1459            0.0       5.6      -1.0   3.4
1460            0.0       5.6      -2.1   3.5

[1461 rows x 4 columns]

In [27]:
Y=df.loc[:,"weather"]
Y

0       0
1       2
2       2
3       2
4       2
       ..
1456    2
1457    2
1458    1
1459    4
1460    4
Name: weather, Length: 1461, dtype: int32

In [28]:
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=.2,random_state=40)

In [29]:
len(xtrain)

1168

In [30]:
len(xtest)

293

In [31]:
xtrain=sc.fit_transform(xtrain)

NameError: name 'sc' is not defined

## Defining & using different models

### Random Forest Classifier

In [32]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=300,max_depth=None)

In [33]:
rfc.fit(xtrain,ytrain)

RandomForestClassifier(n_estimators=300)

In [34]:
pred_rfc=rfc.predict(xtest)
pred_rfc

array([4, 2, 4, 2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4,
       2, 4, 2, 2, 4, 4, 2, 4, 4, 2, 4, 0, 4, 4, 4, 4, 4, 4, 4, 2, 0, 2,
       4, 2, 2, 4, 4, 2, 2, 4, 4, 4, 2, 4, 4, 4, 4, 2, 2, 2, 3, 4, 2, 2,
       4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 2, 2,
       2, 4, 4, 2, 1, 2, 2, 4, 2, 2, 2, 4, 4, 4, 4, 4, 2, 2, 2, 2, 4, 4,
       2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 3, 2, 4, 4, 2, 2, 4, 4, 2, 4, 2, 2,
       2, 2, 4, 2, 2, 4, 4, 2, 4, 4, 4, 4, 2, 2, 2, 2, 2, 4, 2, 4, 2, 4,
       2, 2, 4, 4, 2, 4, 4, 2, 4, 2, 2, 4, 3, 2, 2, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 2, 4, 2, 4, 4, 2, 4, 4, 2, 4, 4, 4, 2, 2, 2, 4, 2, 2,
       4, 4, 2, 2, 2, 4, 4, 4, 2, 4, 4, 2, 2, 2, 2, 4, 4, 4, 2, 4, 4, 2,
       2, 4, 4, 4, 2, 2, 4, 0, 4, 2, 4, 2, 2, 4, 2, 2, 4, 4, 4, 1, 0, 4,
       2, 4, 4, 4, 2, 4, 2, 4, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2, 1,
       2, 2, 4, 4, 4, 2, 4, 4, 2, 4, 2, 1, 2, 2, 4, 4, 1, 2, 4, 2, 2, 4,
       2, 2, 2, 2, 4, 4, 4])

In [35]:
from sklearn.metrics import accuracy_score,confusion_matrix, classification_report


In [36]:
asc=accuracy_score(ytest,pred_rfc)

In [37]:
asc

0.8020477815699659

In [38]:
print(confusion_matrix(ytest,pred_rfc))

[[  2   0   0   0  14]
 [  0   0   0   0  24]
 [  0   1 118   0   7]
 [  0   0   2   3   0]
 [  2   4   4   0 112]]


In [39]:
print(classification_report(ytest,pred_rfc))

              precision    recall  f1-score   support

           0       0.50      0.12      0.20        16
           1       0.00      0.00      0.00        24
           2       0.95      0.94      0.94       126
           3       1.00      0.60      0.75         5
           4       0.71      0.92      0.80       122

    accuracy                           0.80       293
   macro avg       0.63      0.52      0.54       293
weighted avg       0.75      0.80      0.76       293



In [95]:
xsample=df[78:79]
xsample.drop("weather",axis=1,inplace=True)
xsample.drop("date",axis=1,inplace=True)

C:\Users\areek\AppData\Local\Temp\ipykernel_71060\40084745.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xsample.drop("weather",axis=1,inplace=True)
C:\Users\areek\AppData\Local\Temp\ipykernel_71060\40084745.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xsample.drop("date",axis=1,inplace=True)


In [97]:
pred_x=rfc.predict(xsample)
pred_x

array([2])

In [99]:
df.loc[78:79]


date  precipitation  temp_max  temp_min  wind  weather
78  2012-03-19            2.0       7.2      -1.1   3.0        2
79  2012-03-20            3.6       7.8       2.2   6.4        2

####  Accurately predicted the value

### SVM

In [40]:
from sklearn.svm import SVC

In [41]:
svc=SVC()
svc.fit(xtrain,ytrain)

SVC()

In [42]:
pred_svc=svc.predict(xtest)

In [43]:
pred_svc

array([4, 2, 4, 2, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4,
       2, 4, 2, 2, 4, 4, 2, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 2,
       4, 2, 2, 4, 4, 4, 2, 4, 4, 4, 2, 4, 4, 4, 4, 2, 2, 2, 2, 4, 2, 2,
       4, 4, 2, 4, 4, 4, 4, 2, 4, 4, 2, 4, 2, 4, 4, 4, 4, 4, 4, 4, 2, 4,
       2, 4, 4, 2, 4, 2, 2, 4, 2, 4, 2, 4, 4, 4, 4, 4, 2, 2, 2, 4, 4, 4,
       2, 4, 4, 4, 4, 2, 4, 4, 4, 2, 2, 2, 4, 4, 2, 2, 4, 4, 2, 4, 2, 2,
       2, 4, 4, 2, 2, 4, 4, 2, 4, 4, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 2, 4,
       2, 2, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 3, 2, 2, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 2, 4, 2, 4, 4, 2, 4, 4, 2, 4, 4, 4, 2, 2, 2, 4, 2, 2,
       4, 4, 2, 2, 2, 4, 4, 4, 2, 4, 4, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 2,
       2, 4, 4, 4, 4, 2, 4, 4, 4, 2, 4, 2, 2, 4, 4, 2, 4, 4, 4, 2, 4, 4,
       2, 4, 2, 4, 2, 4, 4, 4, 2, 4, 4, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 4,
       2, 4, 4, 4, 4, 2, 4, 4, 2, 4, 2, 4, 2, 2, 4, 4, 4, 2, 4, 2, 2, 2,
       2, 2, 2, 2, 4, 4, 4])

In [44]:
acs1=accuracy_score(ytest,pred_svc)

In [45]:
acs1

0.757679180887372

In [46]:
f1_score(pred_rfc,ytest)

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].